name: goldfolks
description: All-in-one application for the elderly.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.0.0
  cloud_firestore: ^1.0.0
  firebase_core: ^1.0.0
  flushbar: ^1.10.4
  email_validator: ^2.0.1
  email_auth: ^0.0.1+3
  provider: ^5.0.0
  youtube_player_iframe: ^2.2.2
  introduction_screen: ^2.1.0
  rxdart: ^0.27.2
  sembast: ^3.1.1
  path_provider: ^2.0.5
  datetime_picker_formfield: ^2.0.0
  multi_select_flutter: ^4.0.0
  intl: ^0.17.0
  flutter_local_notifications: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: MedicationIcon
      fonts:
        - asset: fonts/MedicationIcon.ttf

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
